# Generated by Django 5.2.2 on 2025-06-10 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        ('task_profiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.question'),
        ),
    ]
