# Generated by Django 5.2.2 on 2025-06-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_profiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='slack_user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
