# Generated by Django 5.2.2 on 2025-06-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_profiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
