# Generated by Django 5.2.2 on 2025-06-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_profiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='timestamp',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
