# Generated by Django 5.2.2 on 2025-06-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_profiler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='slack_user',
            new_name='replier_name',
        ),
        migrations.AddField(
            model_name='reply',
            name='replier_slack_user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
