# Generated by Django 5.2.2 on 2025-06-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_profiler', '0003_cronjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjob',
            name='is_running',
        ),
        migrations.AddField(
            model_name='cronjob',
            name='status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('DISABLED', 'Disabled')], default='IDLE', max_length=10),
        ),
    ]
