# Generated by Django 5.2.2 on 2025-06-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_profiler', '0004_remove_cronjob_is_running_cronjob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjob',
            name='status',
        ),
        migrations.AddField(
            model_name='cronjob',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
