# Generated by Django 5.2.2 on 2025-06-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_profiler', '0005_remove_cronjob_status_cronjob_is_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cron Job Status',
                'verbose_name_plural': 'Cron Job Status',
            },
        ),
        migrations.DeleteModel(
            name='CronJob',
        ),
    ]
