# Generated by Django 5.2.2 on 2025-06-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_profiler', '0006_cronjobstatus_delete_cronjob'),
    ]

    operations = [
        # Drop the existing corrupted table
        migrations.RunSQL("DROP TABLE IF EXISTS task_profiler_cronjobstatus;"),
        
        # Recreate the table with correct schema
        migrations.CreateModel(
            name='CronJobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cron Job Status',
                'verbose_name_plural': 'Cron Job Status',
            },
        ),
    ]
