# Generated by Django 5.2.2 on 2025-06-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
