# Generated by Django 5.2.2 on 2025-06-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_question_pending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='pending',
            new_name='is_pending',
        ),
    ]
