# Generated by Django 5.2.2 on 2025-06-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_topic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
