# Generated by Django 5.2.2 on 2025-06-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_remove_task_description_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slack_channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
