# Generated by Django 5.2.2 on 2025-06-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_workspace_topic_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='workspace',
        ),
    ]
