# Generated by Django 5.2.2 on 2025-06-07 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_remove_topic_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.workspace'),
            preserve_default=False,
        ),
    ]
