# Generated by Django 5.2.2 on 2025-06-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='timestamp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
